import { jsPDF } from 'jspdf'
import type { InterviewSession } from './store'

export function exportSessionPDF(session: InterviewSession) {
  const doc = new jsPDF()
  const margin = 20
  let y = margin

  const addText = (text: string, size: number, bold = false, color: [number, number, number] = [30, 41, 59]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, 170)
    lines.forEach((line: string) => {
      if (y > 270) { doc.addPage(); y = margin }
      doc.text(line, margin, y)
      y += size * 0.5
    })
    y += 2
  }

  const addDivider = () => {
    if (y > 265) { doc.addPage(); y = margin }
    y += 4
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, y, 190, y)
    y += 8
  }

  // Header
  addText('MOSI INTERVIEW REPORT', 18, true, [15, 23, 42])
  y += 2
  addText(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 9, false, [148, 163, 184])
  y += 6

  // Stakeholder info
  addDivider()
  addText('STAKEHOLDER', 8, true, [100, 116, 139])
  y += 2
  addText(session.stakeholder?.name || 'Anonymous', 14, true)
  if (session.stakeholder?.role) addText(`${session.stakeholder.role} at ${session.stakeholder.company || 'N/A'}`, 10, false, [71, 85, 105])
  if (session.stakeholder?.sector) addText(`Sector: ${session.stakeholder.sector}`, 9, false, [100, 116, 139])
  y += 4

  // Session metadata
  addText(`Date: ${session.date}  |  Duration: ${Math.floor(session.duration / 60)}m ${session.duration % 60}s  |  Status: ${session.status}`, 9, false, [100, 116, 139])

  // Summary
  if (session.summary) {
    addDivider()
    addText('EXECUTIVE SUMMARY', 8, true, [100, 116, 139])
    y += 2
    addText(session.summary, 10)
  }

  // Transcript
  if (session.transcriptText) {
    addDivider()
    addText('TRANSCRIPT', 8, true, [100, 116, 139])
    y += 2
    addText(session.transcriptText, 9, false, [51, 65, 85])
  }

  // Opportunities
  if (session.opportunities.length > 0) {
    addDivider()
    addText('OPPORTUNITIES & INSIGHTS', 8, true, [100, 116, 139])
    y += 4

    session.opportunities.forEach((opp, i) => {
      if (y > 255) { doc.addPage(); y = margin }
      addText(`${i + 1}. [${opp.tag}] ${opp.title}`, 10, true)
      if (opp.description) addText(opp.description, 9, false, [71, 85, 105])
      if (opp.duration) addText(`Timeline: ${opp.duration}`, 8, false, [100, 116, 139])
      if (opp.skills) addText(`Skills: ${opp.skills}`, 8, false, [100, 116, 139])
      y += 4
    })
  }

  // Footer
  addDivider()
  addText('This report was generated by MOSI Interview Intelligence Platform.', 8, false, [148, 163, 184])

  // Save
  const fileName = `MOSI_Report_${(session.stakeholder?.name || 'Session').replace(/\s+/g, '_')}_${session.date?.replace(/[,\s]+/g, '_') || 'undated'}.pdf`
  doc.save(fileName)
}
