import { NextResponse } from 'next/server';

// Export config for Next.js to parse the body natively
export const maxDuration = 300; // Allow enough time for transcription

async function transcribeWithElevenLabs(audioBuffer: Buffer): Promise<string> {
  if (!process.env.ELEVENLABS_API_KEY) {
    throw new Error('ELEVENLABS_API_KEY not configured in .env.local');
  }

  const formData = new FormData();
  // Using Uint8Array to avoid Node Buffer/Blob compatibility issues in TS
  const blob = new Blob([new Uint8Array(audioBuffer)], { type: 'audio/webm' });
  formData.append('file', blob, 'recording.webm');
  formData.append('model_id', 'scribe_v1'); 

  console.log('Transcribing with ElevenLabs...');
  const response = await fetch('https://api.elevenlabs.io/v1/speech-to-text', {
    method: 'POST',
    headers: {
      'xi-api-key': process.env.ELEVENLABS_API_KEY,
    },
    body: formData,
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`ElevenLabs Transcription failed: ${errorText}`);
  }

  const data = await response.json();
  console.log('Transcription successful with ElevenLabs.');
  return data.text || '';
}

export async function POST(req: Request) {
  try {
    const contentType = req.headers.get('content-type') || '';
    
    let transcriptText = '';
    let opportunities: any[] = [];
    let stakeholder: any = {};

    if (contentType.includes('multipart/form-data')) {
      console.log('Receiving direct multipart/form-data upload...');
      const formData = await req.formData();
      const rawOpp = formData.get('opportunities') as string;
      const rawStakeholder = formData.get('stakeholder') as string;
      
      opportunities = rawOpp ? JSON.parse(rawOpp) : [];
      stakeholder = rawStakeholder ? JSON.parse(rawStakeholder) : {};
      
      const audioFile = formData.get('audioFile') as File | null;
      
      if (audioFile) {
        console.log('Transcribing local File object with ElevenLabs Scribe...');
        const arrayBuffer = await audioFile.arrayBuffer();
        transcriptText = await transcribeWithElevenLabs(Buffer.from(arrayBuffer));
      }
    } else {
      console.log('Receiving JSON request...');
      const body = await req.json();
      opportunities = body.opportunities || [];
      stakeholder = body.stakeholder || {};
      const recordingUrl = body.recordingUrl;
      
      if (recordingUrl) {
        let fetchUrl = recordingUrl;
        let arrayBuffer: ArrayBuffer | null = null;
        
        console.log('Fetching audio from URL:', fetchUrl);
        
        try {
          const audioResponse = await fetch(fetchUrl);
          if (!audioResponse.ok) throw new Error('Bad status');
          arrayBuffer = await audioResponse.arrayBuffer();
        } catch (primaryErr: any) {
          console.log('Primary fetch failed, attempting Docker fallback routing...', primaryErr.message);
          const fallbackUrl = fetchUrl.includes('127.0.0.1') 
            ? fetchUrl.replace('127.0.0.1', 'localhost') 
            : fetchUrl.replace('localhost', '127.0.0.1');
            
          const fallbackResponse = await fetch(fallbackUrl);
          if (!fallbackResponse.ok) throw new Error('Fallback URL also failed.');
          arrayBuffer = await fallbackResponse.arrayBuffer();
        }

        if (arrayBuffer) {
           transcriptText = await transcribeWithElevenLabs(Buffer.from(arrayBuffer));
        }
      }
    }

    // Synthesis block removed as per user request (GPT not required)
    // We provide the transcript as the summary for now.
    const summary = transcriptText || "No transcription generated by ElevenLabs.";

    return NextResponse.json({ summary, transcript: transcriptText });

  } catch (error: any) {
    console.error('Transcription API Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to process audio with ElevenLabs.' }, { status: 500 });
  }
}


